apiVersion: apps/v1
kind: Deployment 
metadata:
    name: "todo"
spec:
    selector: 
        matchLabels:
            app: "todo-app"
    replicas: 5
    template:
        metadata:
            labels:
                app: "todo-app"
        spec:
            containers:
            - image: {{.Values.image}}
              imagePullPolicy: Always
              name: "todo-app"
              env:
                - name: DB_URL
                  value: mongodb://AWS:password@todo-db-test-docdb-cluster.cluster-ctioohynuogq.us-east-1.docdb.amazonaws.com:27017
              ports:
              - containerPort: 27017
