apiVersion: apps/v1
kind: Deployment 
metadata:
    name: "todo-app"
spec:
    selector: 
        matchLabels:
            app: "task"
    replicas: 5
    template:
        metadata:
            labels:
                app: "task"
        spec:
            containers:
            - image: {{.Values.image}}
              imagePullPolicy: Always
              name: "todoapp"
              env:
                - name: mongodb
                  value: mongodb://{.Values.username}:{.Values.password}@{{ .Values.dbhost }}
              ports:
              - containerPort: 27017
